# Generated by Django 3.1.6 on 2021-02-02 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('explanation', models.TextField()),
                ('answer', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime(2021, 2, 2, 8, 40, 13, 909613, tzinfo=utc))),
                ('viewcnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='BbsUserRegister',
            new_name='UserRegister',
        ),
        migrations.DeleteModel(
            name='Bbs',
        ),
    ]
