# Generated by Django 3.1.6 on 2021-02-03 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0004_auto_20210203_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 16, 19, 24, 60726)),
        ),
    ]
