# Generated by Django 3.1.6 on 2021-02-03 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0005_auto_20210203_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 16, 22, 38, 464435)),
        ),
    ]
