# Generated by Django 3.1.6 on 2021-02-05 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0007_auto_20210205_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 17, 59, 54, 972713)),
        ),
    ]
