# Generated by Django 3.1.6 on 2021-02-06 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0008_auto_20210205_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='viewcnt',
        ),
        migrations.AddField(
            model_name='quiz',
            name='classtype',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 0, 8, 17, 327712)),
        ),
    ]
