# Generated by Django 3.1.6 on 2021-02-07 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0012_auto_20210206_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='classtype',
            new_name='classType',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='regdate',
        ),
        migrations.AddField(
            model_name='quiz',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 0, 13, 31, 72061)),
        ),
    ]
