# Generated by Django 3.1.6 on 2021-02-07 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0013_auto_20210207_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 0, 18, 50, 354760)),
        ),
    ]
