# Generated by Django 3.1.6 on 2021-02-07 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0014_auto_20210207_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='regDate',
        ),
        migrations.AddField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 0, 20, 16, 138685)),
        ),
    ]
