# Generated by Django 3.1.6 on 2021-02-07 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0015_auto_20210207_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='regdate',
        ),
        migrations.AddField(
            model_name='quiz',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 0, 26, 3, 702355)),
        ),
    ]
