--1-1 CUSTOMERS TABLE
CREATE TABLE CUSTOMERS(
    CNO     NUMBER(5) PRIMARY KEY,
    CNAME   VARCHAR2(10) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    EMAIL   VARCHAR2(20) NOT NULL,
    PHONE   VARCHAR2(20) NOT NULL
);

SELECT  *
FROM    CUSTOMERS;
ORDERNO
--1-2 ORDERS TABLE
CREATE TABLE ORDERS(
    ORDER_NO    NUMBER(10) PRIMARY KEY,
    ODER_DATE   DATE DEFAULT SYSDATE NOT NULL,
    ADDRESS     VARCHAR2(50) NOT NULL,
    PHONE       VARCHAR2(20) NOT NULL,
    STATUS      VARCHAR2(20) NOT NULL, CHECK(STATUS IN('결제완료', '배송중', '배송완료')),
    CNO         NUMBER(5) NOT NULL REFERENCES CUSTOMERS(CNO)
);

SELECT  *
FROM    ORDERS;

DROP TABLE ORDERS;
--1-3 PRODUCTS
CREATE TABLE PRODUCTS(
    PNO     NUMBER(5) PRIMARY KEY,
    PNAME   VARCHAR2(20) NOT NULL,
    COST    NUMBER(8) DEFAULT 0 NOT NULL,
    STOCK   NUMBER(5) DEFAULT 0 NOT NULL
    );

SELECT  *
FROM    PRODUCTS;

DROP TABLE PRODUCTS;
--1-4. ORDER_DETAIL
CREATE TABLE ORDER_DETAIL(
    ORDER_NO    NUMBER(10) REFERENCES ODERS(ORDER_NO),
    PNO         NUMBER(5)  REFERENCES PRODUCTS(PNO),
    QTY         NUMBER(5)  DEFAULT 0,
    COST        NUMBER(8)  DEFAULT 0,
    PRIMARY KEY(ORDER_NO, PNO)   
);

DROP TABLE ORDER_DETAIL;